trader:
  strategy:
    ema:
      initial-short-time-frame: 7
      initial-long-time-frame: 14
      short-time-frame-from: 5
      short-time-frame-to: 15
      long-time-frame-from: 12
      long-time-frame-to: 20
